channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=25.1.1
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - tensorflow-intel==2.16.1
  - tensorflow==2.16.1
name: mlflow-env
